export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'
export const POEMS_REPOSITORY = 'POEMS_REPOSITORY'
export const USERS_REPOSITORY = 'USERS_REPOSITORY'

export const DEFAULT_EXPIRATION_TIME_IN_SECONDS = 30 * 86400
export const DEFAULT_EXPIRATION_TIME_IN_MILLISECONDS = 30 * 86400 * 1000
